global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'minio'

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

rule_files:
- minio_rules.yml

scrape_configs:
  - job_name: minio-job
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoibWluaW9hZG1pbiIsImV4cCI6NDg2MTcwMjkwNH0.misoKlVgZ5m4YAKqQcrNoS1-__uipezSygMmTNWmORMUCoPyDFIhONKaZVUJFabP3ZBWLvc-r1lm-YURewWMqw
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
    - targets: ['10.0.2.15:9000']
